import type { Config } from "tailwindcss";

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        navy: {
          900: "#0a1f44",
          800: "#0d2754",
        },
        secondary: "#ecc246",
        outline: "#99907c",
        "on-background": "#e2e2e2",
        "on-secondary-fixed-variant": "#584400",
        "on-tertiary-container": "#534400",
        "inverse-on-surface": "#303030",
        "on-surface": "#e2e2e2",
        "inverse-primary": "#735c00",
        "surface-container-highest": "#353535",
        "on-primary-fixed-variant": "#574500",
        "surface-container": "#1f1f1f",
        "on-error": "#690005",
        "primary-fixed": "#ffe088",
        "surface-tint": "#e9c349",
        "on-primary": "#3c2f00",
        "secondary-fixed-dim": "#ecc246",
        "on-surface-variant": "#d0c5af",
        "on-secondary-fixed": "#241a00",
        "surface-variant": "#353535",
        "inverse-surface": "#e2e2e2",
        primary: "#f2ca50",
        "surface-container-lowest": "#0e0e0e",
        tertiary: "#f2cc00",
        "surface-bright": "#393939",
        "tertiary-container": "#d2b100",
        "surface-container-high": "#2a2a2a",
        error: "#ffb4ab",
        "on-secondary-container": "#352800",
        "on-tertiary-fixed": "#221b00",
        "error-container": "#93000a",
        "tertiary-fixed-dim": "#e9c400",
        surface: "#131313",
        "primary-container": "#d4af37",
        "primary-fixed-dim": "#e9c349",
        "surface-dim": "#131313",
        "on-error-container": "#ffdad6",
        "secondary-container": "#b18c09",
        "on-primary-container": "#554300",
        "on-tertiary-fixed-variant": "#544600",
        "on-secondary": "#3d2e00",
        "on-tertiary": "#3a3000",
        "secondary-fixed": "#ffe08e",
        "surface-container-low": "#1b1b1b",
        "tertiary-fixed": "#ffe16d",
        "outline-variant": "#4d4635",
        "on-primary-fixed": "#241a00",
      },
      spacing: {
        gutter: "2rem",
        "stack-lg": "3rem",
        "stack-sm": "0.5rem",
        "section-padding": "8rem",
        "container-max": "1280px",
        "stack-md": "1.5rem",
      },
      fontFamily: {
        inter: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        "headline-md": ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        "label-sm": ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        "headline-lg": ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        "display-xl": ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-md": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "500" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "28px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" },
        ],
        "headline-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "display-xl": [
          "72px",
          { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
} satisfies Config;
